<a href="https://colab.research.google.com/github/mikhael2104/Kecerdasan-Buatan/blob/main/Jobsheet_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **JOBSHEET 2 - OPERASI MATEMATIKA, VEKTOR, DAN MATRIKS**

## Latihan 1 - Tipe Data Python

In [1]:
var = 123
print(type(var))

<class 'int'>


In [2]:
a = "123"
b = "4.3"
c = "Data String"
print(type(c))

<class 'str'>


In [10]:
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)

sum = var1 + var2
print(sum)

var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)

print("\n",var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

<class 'float'>
345.0
379.5
34
12

 False
False
True
True


In [11]:
list = ["belajar dasar python", 2023, 3.8, True]
print(list)

print(list[3])
print(list[1:3])
print(len(list))

['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


## Latihan 2 - Operasi Matematika menggunakan Python

In [ ]:
#mendapatkan nilai min & maks
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)

In [13]:
#mendapatkan nilai absolut
x = abs(-7.25)
print(x)

7.25


In [14]:
#mendapatkan nilai pangkat
import math
x = math.pow(4, 3)
print(x)

In [17]:
#mendapatkan nilai akar
import math
x = math.sqrt(64)
print(x)

8.0


In [19]:
#mendapatkan nilai pembuatan
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x)
print(y)

2
1


In [20]:
#mendapatkan nilai konstanta
x = math.pi
print(x)

3.141592653589793


## Latihan 3 - Menggunakan Fungsi Math

In [24]:
import math

# 1. Menggunakan Metode .format()
# Bagus untuk mengatur presisi desimal seperti {:.2f}
sudut = math.pi / 4  # 45 derajat
print("math.sin({:.2f})       : {}".format(sudut, math.sin(sudut)))
print("math.cos({:.2f})       : {}".format(sudut, math.cos(sudut)))
print("math.tan({:.2f})       : {}".format(sudut, math.tan(sudut)))

print("-" * 40)

# 2. Menggunakan Koma (,)
# Metode paling sederhana, Python otomatis menambahkan spasi
print("math.log(10)          :", math.log(10))
print("math.log10(100)       :", math.log10(100))

print("-" * 40)

# 3. Konversi & Jarak
print("math.degrees(3.14)    :", math.degrees(math.pi))
titik_a = (0, 0)
titik_b = (3, 4)
print("math.dist(a, b)       :", math.dist(titik_a, titik_b))

print("-" * 40)

# 4. Aljabar & Kombinatorika
n, k = 5, 2
print("math.factorial(5)     :", math.factorial(n))
print("math.perm(5, 2)       :", math.perm(n, k))
print("math.gamma(5)         :", math.gamma(n))

print("-" * 40)

# 5. Numerik Lainnya
print("math.fmod(20, 3)      :", math.fmod(20, 3))
print("math.isnan(NaN)       :", math.isnan(float('nan')))

math.sin(0.79)       : 0.7071067811865475
math.cos(0.79)       : 0.7071067811865476
math.tan(0.79)       : 0.9999999999999999
----------------------------------------
math.log(10)          : 2.302585092994046
math.log10(100)       : 2.0
----------------------------------------
math.degrees(3.14)    : 180.0
math.dist(a, b)       : 5.0
----------------------------------------
math.factorial(5)     : 120
math.perm(5, 2)       : 20
math.gamma(5)         : 24.0
----------------------------------------
math.fmod(20, 3)      : 2.0
math.isnan(NaN)       : True


In [26]:
import math
x = math.sin
y = math.cos
z = math.tan
a = math.log
b = math.log10
c = math.degrees
d = math.dist
e = math.factorial
f = math.fmod
g = math.isnan
h = math.gamma
i = math.perm

# Eksekusi dengan nilai contoh
print("Hasil math.sin(pi/2)      : {}".format(x(math.pi / 2)))
print("Hasil math.cos(0)         : {}".format(y(0)))
print("Hasil math.tan(pi/4)      : {}".format(z(math.pi / 4)))

print("-" * 40)

print("Hasil math.log(2.71)      : {}".format(a(math.e))) # math.e adalah bilangan natural
print("Hasil math.log10(1000)    : {}".format(b(1000)))

print("-" * 40)

print("Hasil math.degrees(pi)    : {}".format(c(math.pi)))
print("Hasil math.dist((0,0),(3,4)): {}".format(d((0, 0), (3, 4))))

print("-" * 40)

print("Hasil math.factorial(5)   : {}".format(e(5)))
print("Hasil math.fmod(10, 3)    : {}".format(f(10, 3)))
print("Hasil math.isnan(NaN)     : {}".format(g(float('nan'))))
print("Hasil math.gamma(6)       : {}".format(h(6))) # Sama dengan 5! (factorial 5)
print("Hasil math.perm(10, 3)    : {}".format(i(10, 3)))

Hasil math.sin(pi/2)      : 1.0
Hasil math.cos(0)         : 1.0
Hasil math.tan(pi/4)      : 0.9999999999999999
----------------------------------------
Hasil math.log(2.71)      : 1.0
Hasil math.log10(1000)    : 3.0
----------------------------------------
Hasil math.degrees(pi)    : 180.0
Hasil math.dist((0,0),(3,4)): 5.0
----------------------------------------
Hasil math.factorial(5)   : 120
Hasil math.fmod(10, 3)    : 1.0
Hasil math.isnan(NaN)     : True
Hasil math.gamma(6)       : 120.0
Hasil math.perm(10, 3)    : 720


## Latihan 4 - Operasi Matriks dan Vektor dengan Python

In [29]:
#membuat matriks di python
import numpy as np
a = np.array([[80, 30, 25], [50, 20, 10]])
b = np.array([[30, 60, 15], [10, 30, 30]])

hasil = a + b
print(hasil)

[[110  90  40]
 [ 60  50  40]]


In [43]:
#melakukan operasi dot product
import numpy as np
a = np.array([10, 20, 15])
b = np.array([16, 67, 35])

hasil = np.dot(a, b)
print(hasil)

2025


In [42]:
#melakukan operasi cross product
import numpy as np
a = np.array([10, 20, 15])
b = np.array([16, 67, 35])

hasil = np.cross(a, b)
print(hasil)

[-305 -110  350]


## Tugas Praktikum

In [41]:
#Soal no
import numpy as np

a = np.array([[3, 1], [2, 0]])
b = np.array([[2, 1], [1, -1]])
c = np.array([[-1, 1, 2], [2, 0, -1]])

hasil1 = a @ b
hasil2 = np.dot(b, c)

print("Hasil dari A x B adalah:", hasil1)
print("Hasil dari A . B adalah:", hasil2)

Hasil dari A x B adalah: [[7 2]
 [4 2]]
Hasil dari A . B adalah: [[ 0  2  3]
 [-3  1  3]]


**Soal no 2** - Hitunglah nilai dari soal berikut: A. 6!, B. 8!/5!

In [38]:
#Soal no 2
import math

a = math.factorial(6)
b = math.factorial(8)/math.factorial(5)

print("Hasil dari 6! adalah:", a)
print("Hasil dari 8!/5! adalah:", b)

Hasil dari 6! adalah: 720
Hasil dari 8!/5! adalah: 336.0


**Soal no 3** - Dua Buah Vektor A dan B merupakan vektor 3D pada koordinat kartesian. Jika Vektor A = 5i + 3j + 7k dan Vektor B = 12i - 3j + k. Maka tentukan panjang masing-masing Vektor, hasil perkalian titik A.B, dan AxB.

In [46]:
import numpy as np

a = np.array([5, 3, 7])
b = np.array([12, 3, 1])

panjangA = np.linalg.norm(a)
panjangB = np.linalg.norm(b)

hasil_dot = np.dot(a, b)
hasil_cross = np.cross(a, b)

print("Panjang Vektor A:", format(panjangA))
print("Panjang Vektor B:", format(panjangB))
print("Hasil dot product A.B: ", format(hasil_dot))
print("Hasil cross product AxB: ", format(hasil_cross))

Panjang Vektor A: 9.1104335791443
Panjang Vektor B: 12.409673645990857
Hasil dot product A.B:  76
Hasil cross product AxB:  [-18  79 -21]
